####
#
#  These examples are generated by parsing https://www.openshift.com/quickstarts/
#
#  To update the current list:
#   - Remove any examples, save, and close
#   - From this directory run: ruby misc/get_quickstarts.rb >> runtime-quickstart.feature
#
#  If there are other quickstarts you would like to test that are not in that list, simply add them with the same format
#  
#  The test output also contains additional profiling/debugging information. To make a Markdown ready table add the following header:
#
#  | Quickstart | Cartridges |  Total Create | Cart Create | Git pull | Quickstart deploy | Second push |
#  | ---------- | ---------- |  ------------ | ----------- | -------- | ----------------- | ----------- |
#
#  - Total create is the time it takes to: create a cartridge, pull the quickstart, push/deploy the quickstart
#  - Second push is accomplished by touching a useless file and pushing again
#
#  If a test fails, the application will be left available and the URL will be printed as well
#
####

@v2
@timed
Feature: Quickstarts
  Background:
    Given a v2 default node

  Scenario Outline: Quickstart Creation Using Manual Method
    Given a new client created <type> application
    And the <qs> quickstart is added
    Then the application should be accessible
    When I push a change to the application
    Then the application should be accessible

  @official
  Examples:
    | qs                                                  | type                   |
    | CodeIgniterQuickStart                               | php-5.3 mysql-5.1      |
    | cakephp-example                                     | php-5.3 mysql-5.1      |
    | capedwarf-example                                   | jbossas-7              |
    | django-example                                      | python-2.6             |
    | dokuwiki-quickstart                                 | php-5.3                |
    | drupal-quickstart                                   | php-5.3 mysql-5.1      |
    | kitchensink-example                                 | jbossas-7              |
    | magento-example                                     | php-5.3 mysql-5.1      |
    | owncloud-openshift-quickstart                       | php-5.3 mysql-5.1      |
    | piwik-openshift-quickstart                          | php-5.3 mysql-5.1      |
    | rails-example                                       | ruby-1.9 mysql-5.1     |
    | spring-eap6-quickstart                              | jbosseap-6.0           |
    | wordpress-example                                   | php-5.3 mysql-5.1      |

  @partner
  Examples:
    | qs                                                  | type                   |
    | KinveyLabs/openshift-kinvey-quickstart              | jbossews-1.0           |
    | OpenMEAP/openshift-openmeap-quickstart              | jbossews-2.0           |
    | developercorey/openshift-wordpress-example-git      | php-5.3 mysql-5.1      |
    | dmueller2001/drupal-quickstart                      | php-5.3 mysql-5.1      |
    | fabianofranz/tiny_tiny_rss-openshift-quickstart     | php-5.3 postgresql-8.4 |
    | iron-io/ironmq-openshift-quickstart                 | ruby-1.9               |
    | keenlabs/keen-io-openshift-quickstart               | ruby-1.9               |
    | leegraham/cakeStrap-example                         | php-5.3 mysql-5.1      |
    | mmahut/statusnet-quickstart                         | php-5.3 mysql-5.1      |
    | mongolab/mongolab-openshift-quickstart              | nodejs-0.6             |
    | nodefly/nodefly-openshift-quickstart                | nodejs-0.6             |
    | nodetime/nodetime-openshift-quickstart              | nodejs-0.6             |
    | openshift-quickstart/reveal.js-openshift-quickstart | php-5.3                |
    | pubnub/pubnub-openshift-quickstart                  | python-2.7             |
    | pusher/pusher-node-openshift-quickstart             | nodejs-0.6             |
    | pusher/pusher-php-openshift-quickstart              | php-5.3                |
    | sendgrid/openshift-sendgrid-php                     | php-5.3                |
    | treasure-data/treasure-data-openshift-quickstart    | ruby-1.9               |
